apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-virtualized
spec:
  destination:
    namespace: tutorial
    name: recommendation
  match:
    source:
      name: preference
      labels:
        version: v2
  precedence: 2
  route:
  - labels:
      version: virtualized
    weight: 100
