apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-mirror
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 2
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0
  mirror:
    namespace: tutorial
    name: recommendation
    labels:
      version: v2
